version: 2
jobs:
  build:
    docker:
      - image: beanstalkg/beanstalkg_build:v0.03

    working_directory: /go/src/github.com/vimukthi-git/beanstalkg

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Run unit tests
          environment:
            #CONTACTS_DB_URL: "postgres://ubuntu@localhost:5432/contacts?sslmode=disable"
            #CONTACTS_DB_MIGRATIONS: /go/src/github.com/circleci/cci-demo-go/db/migrations
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go get github.com/vimukthi-git/beanstalkg
            go test -v ./... | tee ${TEST_RESULTS}/go-test.out

      - deploy:
          name: Conditionally run docker push. i.e if this is a release branch
          command: |
            release_regex='^v([0-9]+\.){0,2}(\*|[0-9]+)$'
            if [[ $CIRCLE_BRANCH =~ $release_regex ]]; then
              curl --user ${CIRCLE_API_TOKEN}: \
                --data build_parameters[CIRCLE_JOB]=deploy_docker \
                --data revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
            fi

      #- run:
          #name: Run integration tests
          #command: |

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

  deploy_docker:
    docker:
      - image: beanstalkg/beanstalkg_build:v0.03
    working_directory: /go/src/github.com/vimukthi-git/beanstalkg
    steps:
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker build
          command: |
            CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /beanstalkg .
            docker build -t "beanstalkg:${CIRCLE_BRANCH}" .
            docker tag beanstalkg:$CIRCLE_BRANCH beanstalkg/beanstalkg:$CIRCLE_BRANCH
            docker push beanstalkg/beanstalkg:$CIRCLE_BRANCH


